# Generated by Django 2.2.1 on 2019-05-21 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('priority', models.IntegerField(choices=[(1, 'low'), (2, 'medium'), (3, 'high')], default=1)),
                ('state', models.IntegerField(choices=[(1, 'new'), (2, 'accepted'), (3, 'completed'), (4, 'declined'), (5, 'cancelled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('store_name', models.CharField(max_length=50)),
                ('user_type', models.IntegerField(choices=[(1, 'manager'), (2, 'rider')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'new'), (2, 'accepted'), (3, 'completed'), (4, 'declined'), (5, 'cancelled')], default=1)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='delivery.Tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='delivery.UserProfile'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='served_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='delivery.UserProfile'),
        ),
    ]
